name: Node.js Package

on:
  push:
      branches:
        - feature/**
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: '00000000-0000-0000-0000-000000000000'
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #     NPM_TOKEN: '00000000-0000-0000-0000-000000000000'
